### ISSUE TITLE
Support multichannel audio output

### ISSUE THREAD

**Issue by asc3ns10n** [maxpiva/Sushi.Net#1]
Multichannel audio is currently being downsampled to stereo. I think it's because the channel layout is not being specified for the anullsrc filter. 

[log](https://github.com/maxpiva/Sushi.Net/files/5884993/log.txt)

**Comment by maxpiva** [comment]
Thanks for the report @asc3ns10n, will try to fix it for the version.

**Comment by maxpiva** [comment]
Support added in 1.0.0
